/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments.$slug'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as GamesIdRouteImport } from './routes/games.$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminGameTypesRouteImport } from './routes/admin.game-types'
import { Route as GamesIdRegisterTimeRouteImport } from './routes/games.$id.register-time'
import { Route as GamesIdBracketRouteImport } from './routes/games.$id.bracket'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminTournamentsNewRouteImport } from './routes/admin.tournaments.new'
import { Route as AdminPlayersNewRouteImport } from './routes/admin.players.new'
import { Route as AdminGamesNewRouteImport } from './routes/admin.games.new'
import { Route as AdminTournamentsIdEditRouteImport } from './routes/admin.tournaments.$id.edit'
import { Route as AdminPlayersIdEditRouteImport } from './routes/admin.players.$id.edit'
import { Route as AdminGamesIdEditRouteImport } from './routes/admin.games.$id.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/tournaments/$slug',
  path: '/tournaments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameTypesRoute = AdminGameTypesRouteImport.update({
  id: '/game-types',
  path: '/game-types',
  getParentRoute: () => AdminRoute,
} as any)
const GamesIdRegisterTimeRoute = GamesIdRegisterTimeRouteImport.update({
  id: '/register-time',
  path: '/register-time',
  getParentRoute: () => GamesIdRoute,
} as any)
const GamesIdBracketRoute = GamesIdBracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => GamesIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsNewRoute = AdminTournamentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTournamentsRoute,
} as any)
const AdminPlayersNewRoute = AdminPlayersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPlayersRoute,
} as any)
const AdminGamesNewRoute = AdminGamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminGamesRoute,
} as any)
const AdminTournamentsIdEditRoute = AdminTournamentsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminTournamentsRoute,
} as any)
const AdminPlayersIdEditRoute = AdminPlayersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPlayersRoute,
} as any)
const AdminGamesIdEditRoute = AdminGamesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/game-types': typeof AdminGameTypesRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/games/$id': typeof GamesIdRouteWithChildren
  '/players/$id': typeof PlayersIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/players/new': typeof AdminPlayersNewRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$id/bracket': typeof GamesIdBracketRoute
  '/games/$id/register-time': typeof GamesIdRegisterTimeRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
  '/admin/players/$id/edit': typeof AdminPlayersIdEditRoute
  '/admin/tournaments/$id/edit': typeof AdminTournamentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin/game-types': typeof AdminGameTypesRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/games/$id': typeof GamesIdRouteWithChildren
  '/players/$id': typeof PlayersIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/players': typeof PlayersIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/players/new': typeof AdminPlayersNewRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$id/bracket': typeof GamesIdBracketRoute
  '/games/$id/register-time': typeof GamesIdRegisterTimeRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
  '/admin/players/$id/edit': typeof AdminPlayersIdEditRoute
  '/admin/tournaments/$id/edit': typeof AdminTournamentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/game-types': typeof AdminGameTypesRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/games/$id': typeof GamesIdRouteWithChildren
  '/players/$id': typeof PlayersIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/players/new': typeof AdminPlayersNewRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$id/bracket': typeof GamesIdBracketRoute
  '/games/$id/register-time': typeof GamesIdRegisterTimeRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
  '/admin/players/$id/edit': typeof AdminPlayersIdEditRoute
  '/admin/tournaments/$id/edit': typeof AdminTournamentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/admin/game-types'
    | '/admin/games'
    | '/admin/login'
    | '/admin/players'
    | '/admin/tournaments'
    | '/api/upload'
    | '/games/$id'
    | '/players/$id'
    | '/tournaments/$slug'
    | '/admin/'
    | '/players/'
    | '/admin/games/new'
    | '/admin/players/new'
    | '/admin/tournaments/new'
    | '/api/auth/$'
    | '/games/$id/bracket'
    | '/games/$id/register-time'
    | '/admin/games/$id/edit'
    | '/admin/players/$id/edit'
    | '/admin/tournaments/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin/game-types'
    | '/admin/games'
    | '/admin/login'
    | '/admin/players'
    | '/admin/tournaments'
    | '/api/upload'
    | '/games/$id'
    | '/players/$id'
    | '/tournaments/$slug'
    | '/admin'
    | '/players'
    | '/admin/games/new'
    | '/admin/players/new'
    | '/admin/tournaments/new'
    | '/api/auth/$'
    | '/games/$id/bracket'
    | '/games/$id/register-time'
    | '/admin/games/$id/edit'
    | '/admin/players/$id/edit'
    | '/admin/tournaments/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/admin/game-types'
    | '/admin/games'
    | '/admin/login'
    | '/admin/players'
    | '/admin/tournaments'
    | '/api/upload'
    | '/games/$id'
    | '/players/$id'
    | '/tournaments/$slug'
    | '/admin/'
    | '/players/'
    | '/admin/games/new'
    | '/admin/players/new'
    | '/admin/tournaments/new'
    | '/api/auth/$'
    | '/games/$id/bracket'
    | '/games/$id/register-time'
    | '/admin/games/$id/edit'
    | '/admin/players/$id/edit'
    | '/admin/tournaments/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  GamesIdRoute: typeof GamesIdRouteWithChildren
  PlayersIdRoute: typeof PlayersIdRoute
  TournamentsSlugRoute: typeof TournamentsSlugRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/tournaments/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game-types': {
      id: '/admin/game-types'
      path: '/game-types'
      fullPath: '/admin/game-types'
      preLoaderRoute: typeof AdminGameTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/games/$id/register-time': {
      id: '/games/$id/register-time'
      path: '/register-time'
      fullPath: '/games/$id/register-time'
      preLoaderRoute: typeof GamesIdRegisterTimeRouteImport
      parentRoute: typeof GamesIdRoute
    }
    '/games/$id/bracket': {
      id: '/games/$id/bracket'
      path: '/bracket'
      fullPath: '/games/$id/bracket'
      preLoaderRoute: typeof GamesIdBracketRouteImport
      parentRoute: typeof GamesIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/new': {
      id: '/admin/tournaments/new'
      path: '/new'
      fullPath: '/admin/tournaments/new'
      preLoaderRoute: typeof AdminTournamentsNewRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
    '/admin/players/new': {
      id: '/admin/players/new'
      path: '/new'
      fullPath: '/admin/players/new'
      preLoaderRoute: typeof AdminPlayersNewRouteImport
      parentRoute: typeof AdminPlayersRoute
    }
    '/admin/games/new': {
      id: '/admin/games/new'
      path: '/new'
      fullPath: '/admin/games/new'
      preLoaderRoute: typeof AdminGamesNewRouteImport
      parentRoute: typeof AdminGamesRoute
    }
    '/admin/tournaments/$id/edit': {
      id: '/admin/tournaments/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/tournaments/$id/edit'
      preLoaderRoute: typeof AdminTournamentsIdEditRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
    '/admin/players/$id/edit': {
      id: '/admin/players/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/players/$id/edit'
      preLoaderRoute: typeof AdminPlayersIdEditRouteImport
      parentRoute: typeof AdminPlayersRoute
    }
    '/admin/games/$id/edit': {
      id: '/admin/games/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/games/$id/edit'
      preLoaderRoute: typeof AdminGamesIdEditRouteImport
      parentRoute: typeof AdminGamesRoute
    }
  }
}

interface AdminGamesRouteChildren {
  AdminGamesNewRoute: typeof AdminGamesNewRoute
  AdminGamesIdEditRoute: typeof AdminGamesIdEditRoute
}

const AdminGamesRouteChildren: AdminGamesRouteChildren = {
  AdminGamesNewRoute: AdminGamesNewRoute,
  AdminGamesIdEditRoute: AdminGamesIdEditRoute,
}

const AdminGamesRouteWithChildren = AdminGamesRoute._addFileChildren(
  AdminGamesRouteChildren,
)

interface AdminPlayersRouteChildren {
  AdminPlayersNewRoute: typeof AdminPlayersNewRoute
  AdminPlayersIdEditRoute: typeof AdminPlayersIdEditRoute
}

const AdminPlayersRouteChildren: AdminPlayersRouteChildren = {
  AdminPlayersNewRoute: AdminPlayersNewRoute,
  AdminPlayersIdEditRoute: AdminPlayersIdEditRoute,
}

const AdminPlayersRouteWithChildren = AdminPlayersRoute._addFileChildren(
  AdminPlayersRouteChildren,
)

interface AdminTournamentsRouteChildren {
  AdminTournamentsNewRoute: typeof AdminTournamentsNewRoute
  AdminTournamentsIdEditRoute: typeof AdminTournamentsIdEditRoute
}

const AdminTournamentsRouteChildren: AdminTournamentsRouteChildren = {
  AdminTournamentsNewRoute: AdminTournamentsNewRoute,
  AdminTournamentsIdEditRoute: AdminTournamentsIdEditRoute,
}

const AdminTournamentsRouteWithChildren =
  AdminTournamentsRoute._addFileChildren(AdminTournamentsRouteChildren)

interface AdminRouteChildren {
  AdminGameTypesRoute: typeof AdminGameTypesRoute
  AdminGamesRoute: typeof AdminGamesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlayersRoute: typeof AdminPlayersRouteWithChildren
  AdminTournamentsRoute: typeof AdminTournamentsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGameTypesRoute: AdminGameTypesRoute,
  AdminGamesRoute: AdminGamesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlayersRoute: AdminPlayersRouteWithChildren,
  AdminTournamentsRoute: AdminTournamentsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GamesIdRouteChildren {
  GamesIdBracketRoute: typeof GamesIdBracketRoute
  GamesIdRegisterTimeRoute: typeof GamesIdRegisterTimeRoute
}

const GamesIdRouteChildren: GamesIdRouteChildren = {
  GamesIdBracketRoute: GamesIdBracketRoute,
  GamesIdRegisterTimeRoute: GamesIdRegisterTimeRoute,
}

const GamesIdRouteWithChildren =
  GamesIdRoute._addFileChildren(GamesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  GamesIdRoute: GamesIdRouteWithChildren,
  PlayersIdRoute: PlayersIdRoute,
  TournamentsSlugRoute: TournamentsSlugRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
